package com.ptm.api.integration.mgmt.constant;

public enum KycConstant {

	ICICI, YESBANK, AEPS_ONBOARD_STATUS,
	ICICI_OUTLET_REGISTRATION_OTP, ICICI_OUTLET_REGISTRATION, ICICI_UPLOAD_KYC_DOCUMENT, ICICI_GET_KYC_STATUS,
	YESBANK_AEPS_REGISTRATION, YESBANK_GET_KYC_STATUS, YESBANK_AEPS_KYC_UPDATE
}
